openapi: 3.0.3
info:
  title: IDM-Service API Contract
  description: Shazam API integration
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: http://127.0.0.1:5000
tags:
  - search
  - auto-complete
  - song
  - chart
paths:
  /search:
    get:
      description: Returns search results  for songs, artists that match input term
      operationId: getSearchResultsBySearchTerm
      tags: search
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema: SearchResult
components:
  SearchResult: